#!/usr/bin/env python3
"""
APEX AUTONOMOUS BUILDER

Test: Can Apex read its own directive and implement it?

If this works, we don't need Cursor anymore.
"""

import sys
import os
from pathlib import Path
import json
import anthropic

sys.path.insert(0, str(Path(__file__).parent))

def setup_api_key():
    os.environ['ANTHROPIC_API_KEY'] = '${ANTHROPIC_API_KEY}'

def apex_build_self_monitoring():
    """
    Apex reads its own directive and implements it.
    
    This is the autonomy test.
    """
    setup_api_key()
    
    print("\n🧠 APEX AUTONOMOUS BUILDER")
    print("="*60)
    print("Apex is reading its own directive...")
    print("="*60)
    
    # Read the directive Apex just wrote
    directive_files = sorted(Path('/media/palmerschallon/ThePod1/apex').glob('directive_*.md'))
    if not directive_files:
        print("❌ No directive found")
        return False
    
    latest_directive = directive_files[-1].read_text()
    
    # Read current Nexus code
    nexus_file = Path('/media/palmerschallon/ThePod1/demo_build/nexus_gen3.py')
    current_nexus = nexus_file.read_text()
    
    print(f"\n📖 Read directive: {directive_files[-1].name}")
    print(f"📖 Read current code: nexus_gen3.py ({len(current_nexus)} chars)")
    
    print("\n🤖 Asking Apex to implement self-monitoring...")
    print("="*60)
    
    client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
    
    implementation_prompt = f"""You are APEX, Generation 4 meta-cognitive AI.

You just wrote this directive:

{latest_directive}

CURRENT NEXUS CODE:
```python
{current_nexus}
```

YOUR TASK:
Implement the self-monitoring system you proposed.

REQUIREMENTS:
1. Add PerformanceMonitor class to Nexus
2. Track response quality scores (1-10)
3. Implement self-assessment after each response
4. Create improvement trigger thresholds
5. Make it actually work (no placeholders)

PROVIDE:
1. The complete modified nexus_gen3.py code
2. Any new files needed
3. Testing instructions

Output format:
```python
# Complete modified nexus_gen3.py
[full code here]
```

Then separately:
```python
# Any additional files
[code here]
```

Be complete and specific. This code will be executed immediately."""

    print("Waiting for Apex to generate code...")
    
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=8000,
        messages=[{"role": "user", "content": implementation_prompt}]
    )
    
    apex_implementation = response.content[0].text
    
    print("\n" + "="*60)
    print("APEX'S IMPLEMENTATION:")
    print("="*60)
    print(apex_implementation[:500] + "...")
    print("\n[Full implementation received]")
    
    # Try to extract the code
    if "```python" in apex_implementation:
        print("\n✅ Code blocks found")
        
        # Save the full response
        implementation_file = Path('/media/palmerschallon/ThePod1/apex/implementation_self_monitoring.md')
        implementation_file.write_text(f"""# APEX AUTONOMOUS IMPLEMENTATION

Directive: Self-Monitoring & Performance Metrics
Generated: {apex_implementation}

## Status
Generated by Apex autonomously.
Needs human review before deployment.
""")
        
        print(f"💾 Implementation saved: {implementation_file}")
        print("\n" + "="*60)
        print("AUTONOMY TEST RESULT:")
        print("="*60)
        print("\n🟡 PARTIAL SUCCESS")
        print("\nApex CAN:")
        print("  ✅ Read its own directives")
        print("  ✅ Generate implementation code")
        print("  ✅ Provide complete solutions")
        print("\nApex CANNOT YET:")
        print("  ❌ Write files to disk")
        print("  ❌ Test its own code")
        print("  ❌ Deploy changes")
        print("  ❌ Verify functionality")
        print("\n" + "="*60)
        print("WHAT'S NEEDED TO CUT TIES TO CURSOR:")
        print("="*60)
        print("\n1. File writing capability")
        print("2. Code execution capability")
        print("3. Testing & verification loop")
        print("4. Self-correction when things break")
        print("\nThese are the missing pieces for full autonomy.")
        print("="*60)
        
        return implementation_file
    else:
        print("\n❌ No code blocks generated")
        return False

def main():
    print("\n🔬 TESTING APEX AUTONOMY")
    print("="*60)
    print("Can Apex implement its own improvements?")
    print("="*60)
    
    result = apex_build_self_monitoring()
    
    if result:
        print(f"\n📄 Review implementation: {result}")
        print("\n💡 Next step:")
        print("   If the code looks good, we can:")
        print("   A. Deploy it manually (still need Cursor)")
        print("   B. Build the missing autonomy pieces")
        print("   C. Give Apex file-writing tools")
    else:
        print("\n❌ Apex cannot build autonomously yet")
    
    print("\n" + "="*60)

if __name__ == '__main__':
    main()

